blank_issues_enabled: true
contact_links:
  - name: Feature/improvement request for overall CORTX project
    url: https://github.com/Seagate/cortx/issues/new?assignees=&labels=enhancement&template=enhancement.yml
    about: Want to suggest an idea for CORTX? Create a feature/improvement request.
  - name: CORTX Questions and Support
    url: https://github.com/Seagate/cortx/discussions
    about: Have questions or need support for CORTX for anything that isn't a bug report? Go ahead and start a new discussion.
  - name: CORTX Community Support
    url: https://cortx.link/slack_invite
    about: Join us on Slack for general CORTX questions and support.
