blank_issues_enabled: true
contact_links:
  - name: Feature request for overall CORTX project
    url: https://github.com/Seagate/cortx/issues/new?assignees=&labels=enhancement&template=enhancement.yml
    about: Want to suggest an idea for the overall CORTX project? Create a feature/improvement request.
  - name: CORTX community questions and support via GitHub Discussions
    url: https://github.com/Seagate/cortx/discussions
    about: Have questions or need support for anything else? Please start a new discussion.
  - name: CORTX community questions and support via Slack
    url: https://cortx.link/slack_invite
    about: Or please ask us on Slack.
